### ISSUE TITLE
Package rename

### ISSUE THREAD

**Issue by favoyang** [TORISOUP/Pun2Task#2]
@TORISOUP

Favo from OpenUPM. Since you renamed package name from net.torisoup.pun2task to com.torisoup.pun2task. It will take up to 30 minutes until the [change](https://github.com/openupm/openupm/commit/cdc40188b72fc1a0634dfb90e14b4fdd51b8dec0) applied to the website.

**Comment by favoyang** [comment]
It's available on https://openupm.com/packages/com.torisoup.pun2task/?subPage=pipelines

**Comment by TORISOUP** [comment]
THX!
